<!--
  ============================================================
  Implementing and Adding a Message Feed Page Using Vue Router
  ============================================================
  We are going to create a new page that displays a list of messages to the user. 
  Users will be able to visit this page whenever they enter the "localhost:5173/messages" path in the browser.

  1. We create a new view component called MessageFeed by adding a MessageFeed.vue file to the ./src/views/ folder.
  2. In MessageFeed.vue:
      a. The component will render a list of messages. 
      Our message list is defined as an array of strings called messages.
  3. There should be an index.js router file located at src/router/index.js. 
  4. In index.js:
      a. There should be a router instance with a routes array.
      b. Declare a route designated for MessageFeed, named messageFeed and with its path set to /messages. 
          We do this by appending an object with the required information to the routes array.
  5. In your browser, visit localhost:5173/messages.
      The page should appear with the correct content – the Message Feed page.
  6. 'router-view' is in charge of rendering the correct active view content relative to the URL path while 
      'router-link' is a Vue component that helps users to navigate within an app that has routing enabled. 
      By default, it renders an anchor tag <a> with a correct href link generated by its to prop.

      In App.vue:
      Add a navigation link to the message feed route. (Follow the Home and About examples).
  7. Save and in your browser, you should see a Messages link. Use it to visit the Message Feed.
  8. We can also specify a router link by bind a location descriptor object to the its "to" prop, e.g., for the 
      'About' link, we could have written:

          <router-link :to="{ name: 'About' }">About</router-link>
    
    The name should be that which you specified in the routes array in index.js.
  9. Use this format for the message feed and verify it still works.
-->
<script setup>
import { RouterLink, RouterView } from "vue-router";
// import HelloWorld from './components/HelloWorld.vue'
</script>

<template>
  <div id="nav">
    <router-link to="/">Home</router-link> |
    <router-link to="/about">About</router-link> |
    <!-- FIX -->
    <router-link ???>Messages</router-link> 
    <!-- | <router-link :to="{ ??? }">MessageFeed</router-link> -->
  </div>
  <!-- <router-view/> -->
  <RouterView />
</template>

<style>
#app {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
}

#nav {
  padding: 30px;
}

#nav a {
  font-weight: bold;
  color: #2c3e50;
}

#nav a.router-link-exact-active {
  color: #42b983;
}
</style>
